"""
Django settings for news_searcher project.

Generated by 'django-admin startproject' using Django 3.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-m18-4+p_f7edt^8zz8@1c7qz*d#hbp44t58#qm_g+_eq413i6*'

# SECURITY WARNING: don't run with debug turned on in production!
# 开发完成后一定要关闭debug模式！！！
DEBUG = True
# DEBUG = False

ALLOWED_HOSTS = ['*', ]

# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'searchApp',
    'django_apscheduler',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'news_searcher.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'news_searcher.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'news_searcher',
        'HOST': '127.0.0.1',
        'PORT': 3306,
        'USER': 'root',
        'PASSWORD': 'root',
        'OPTIONS': {
            "init_command": "set default_storage_engine='InnoDB'",
            'charset': 'utf8mb4',
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

# USE_TZ = True
USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

SIMPLEUI_LOGIN_PARTICLES = False

SIMPLEUI_LOGO = '/static/img/logo_icon.png'

SIMPLEUI_HOME_INFO = False

SIMPLEUI_HOME_ACTION = True

SIMPLEUI_HOME_PAGE = '/admin/sys/bigscreen/'

SIMPLEUI_HOME_TITLE = '首页'

SIMPLEUI_HOME_ICON = 'fa fa-home'

SIMPLEUI_DEFAULT_THEME = 'element.css'

SIMPLEUI_DEFAULT_ICON = False

SIMPLEUI_CONFIG = {
    # 是否使用系统默认菜单，自定义菜单时建议关闭。
    'system_keep': False,
    # 用于菜单排序和过滤, 不填此字段为默认排序和全部显示。空列表[] 为全部不显示.
    'menu_display': ['认证授权', '新闻管理', '工单管理', '系统管理', '数据看板'],

    # 设置是否开启动态菜单, 默认为False. 如果开启, 则会在每次用户登陆时刷新展示菜单内容。
    # 一般建议关闭。
    'dynamic': False,
    'menus': [
        {
            'app': 'auth',
            'name': '认证授权',
            'icon': 'fa fa-user-shield',
            'models': [
                {
                    'name': '用户',
                    'icon': 'fa fa-user',
                    'url': 'auth/user/'
                },
                {
                    'name': '组',
                    'icon': 'fa fa-table-list',
                    'url': 'auth/group/'
                }
            ]
        },
        {
            'app': 'news',
            'name': '新闻管理',
            'icon': 'fa fa-newspaper',
            'models': [
                {
                    'name': '新闻列表',
                    'icon': 'fa fa-file-lines',
                    'url': 'searchApp/article/'
                },
                {
                    'name': '新闻类型',
                    'icon': 'fa fa-bars',
                    'url': 'searchApp/articletype/'
                },
                {
                    'name': '新闻来源',
                    'icon': 'fa fa-paperclip',
                    'url': 'searchApp/sourcesite/'
                },
            ]
        },
        {
            'app': 'document',
            'name': '工单管理',
            'icon': 'fa fa-file-pen',
            'models': [
                {
                    'name': '工单处理',
                    'icon': 'fa fa-spinner',
                    'url': 'searchApp/documentprocess/'
                },
            ]
        },
        {
            'app': 'sys',
            'name': '系统管理',
            'icon': 'fa fa-shield-halved',
            'models': [
                {
                    'name': '系统升级',
                    'icon': 'fa fa-circle-up',
                    'url': 'sys/update/'
                },
                {
                    'name': '系统测试',
                    'icon': 'fa fa-vial',
                    'url': '../'
                },
                {
                    'name': '升级日志',
                    'icon': 'fa fa-pen-to-square',
                    'url': 'searchApp/patchlog/'
                },
                {
                    'name': '搜索日志',
                    'icon': 'fa fa-eye',
                    'url': 'searchApp/searchlog/'
                },
                {
                    'name': '版本信息',
                    'icon': 'fa fa-code-branch',
                    'url': 'sys/version/'
                },
            ]
        },
        {
            'app': 'bigdata',
            'name': '数据看板',
            'icon': 'fa fa-tv',
            'models': [
                {
                    'name': '数据看板',
                    'icon': 'fa fa-display',
                    'url': 'sys/bigscreen/'
                },
            ]
        },
    ]
}
