# Generated by Django 3.2.16 on 2022-12-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=36, null=True)),
                ('source', models.CharField(max_length=36, null=True)),
                ('tags', models.TextField(null=True)),
                ('title', models.TextField(null=True)),
                ('content', models.TextField(null=True)),
                ('pic', models.CharField(max_length=256, null=True)),
                ('url', models.CharField(max_length=256, null=True)),
                ('publishtime', models.DateTimeField(null=True)),
                ('pageview', models.IntegerField(null=True)),
                ('state_isenabled', models.CharField(max_length=1, null=True)),
                ('timestamp_createdby', models.CharField(max_length=36, null=True)),
                ('timestamp_createdon', models.DateTimeField(null=True)),
                ('timestamp_lastchangedby', models.CharField(max_length=36, null=True)),
                ('timestamp_lastchangedon', models.DateTimeField(null=True)),
                ('txt01', models.TextField(null=True)),
                ('txt02', models.TextField(null=True)),
                ('num01', models.IntegerField(null=True)),
                ('num02', models.IntegerField(null=True)),
                ('time01', models.DateTimeField(null=True)),
                ('time02', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('icon', models.CharField(max_length=256, null=True)),
                ('state_isenabled', models.CharField(max_length=1, null=True)),
                ('timestamp_createdby', models.CharField(max_length=36, null=True)),
                ('timestamp_createdon', models.DateTimeField(null=True)),
                ('timestamp_lastchangedby', models.CharField(max_length=36, null=True)),
                ('timestamp_lastchangedon', models.DateTimeField(null=True)),
                ('txt01', models.TextField(null=True)),
                ('num01', models.IntegerField(null=True)),
                ('time01', models.DateTimeField(null=True)),
                ('sysinit', models.CharField(max_length=1, null=True)),
            ],
            options={
                'db_table': 'articletype',
            },
        ),
        migrations.CreateModel(
            name='SourceSite',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('icon', models.CharField(max_length=256, null=True)),
                ('url', models.CharField(max_length=256, null=True)),
                ('state_isenabled', models.CharField(max_length=1, null=True)),
                ('timestamp_createdby', models.CharField(max_length=36, null=True)),
                ('timestamp_createdon', models.DateTimeField(null=True)),
                ('timestamp_lastchangedby', models.CharField(max_length=36, null=True)),
                ('timestamp_lastchangedon', models.DateTimeField(null=True)),
                ('txt01', models.TextField(null=True)),
                ('num01', models.IntegerField(null=True)),
                ('time01', models.DateTimeField(null=True)),
                ('sysinit', models.CharField(max_length=1, null=True)),
            ],
            options={
                'db_table': 'sourcesite',
            },
        ),
    ]
