# Generated by Django 3.2.16 on 2022-12-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0002_articletype_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletype',
            name='sortorder',
            field=models.IntegerField(null=True),
        ),
    ]
