# Generated by Django 3.2.16 on 2022-12-27 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0003_articletype_sortorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articletype',
            old_name='site',
            new_name='code',
        ),
    ]
