# Generated by Django 3.2.16 on 2022-12-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0004_rename_site_articletype_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatchLog',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=36, null=True)),
                ('info', models.TextField(null=True)),
                ('patchtime', models.DateTimeField(null=True)),
                ('creator', models.CharField(max_length=36, null=True)),
            ],
            options={
                'db_table': 'patchlog',
            },
        ),
    ]
