# Generated by Django 3.2.16 on 2022-12-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0005_patchlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletype',
            name='showindex',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
