# Generated by Django 3.2.16 on 2022-12-31 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0006_articletype_showindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentProcess',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=36, null=True)),
                ('info', models.TextField(null=True)),
                ('status', models.CharField(max_length=1, null=True)),
                ('createtime', models.DateTimeField(null=True)),
                ('reviewer', models.CharField(max_length=36, null=True)),
            ],
            options={
                'db_table': 'documentprocess',
            },
        ),
    ]
