# Generated by Django 3.2.16 on 2023-01-01 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0007_documentprocess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.CharField(max_length=36, primary_key=True, serialize=False, unique=True, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(null=True, verbose_name='标题'),
        ),
    ]
