# Generated by Django 3.2.16 on 2023-01-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0009_auto_20230101_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentprocess',
            name='relatedid',
            field=models.CharField(max_length=36, null=True, verbose_name='关联ID'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(null=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pageview',
            field=models.IntegerField(null=True, verbose_name='浏览量'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pic',
            field=models.CharField(max_length=256, null=True, verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publishtime',
            field=models.DateTimeField(null=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='source',
            field=models.CharField(max_length=36, null=True, verbose_name='来源'),
        ),
        migrations.AlterField(
            model_name='article',
            name='state_isenabled',
            field=models.CharField(max_length=1, null=True, verbose_name='是否可用'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.TextField(null=True, verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='article',
            name='timestamp_createdby',
            field=models.CharField(max_length=36, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='article',
            name='timestamp_createdon',
            field=models.DateTimeField(null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='timestamp_lastchangedby',
            field=models.CharField(max_length=36, null=True, verbose_name='修改者'),
        ),
        migrations.AlterField(
            model_name='article',
            name='timestamp_lastchangedon',
            field=models.DateTimeField(null=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(null=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(max_length=36, null=True, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.CharField(max_length=256, null=True, verbose_name='原文链接'),
        ),
        migrations.AlterField(
            model_name='articletype',
            name='code',
            field=models.CharField(max_length=36, null=True, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='articletype',
            name='icon',
            field=models.CharField(max_length=256, null=True, verbose_name='图标'),
        ),
        migrations.AlterField(
            model_name='articletype',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='articletype',
            name='showindex',
            field=models.CharField(max_length=1, null=True, verbose_name='主页显示'),
        ),
        migrations.AlterField(
            model_name='articletype',
            name='sortorder',
            field=models.IntegerField(null=True, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='articletype',
            name='state_isenabled',
            field=models.CharField(max_length=1, null=True, verbose_name='是否可用'),
        ),
        migrations.AlterField(
            model_name='articletype',
            name='sysinit',
            field=models.CharField(max_length=1, null=True, verbose_name='系统预置'),
        ),
        migrations.AlterField(
            model_name='articletype',
            name='timestamp_createdby',
            field=models.CharField(max_length=36, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='articletype',
            name='timestamp_createdon',
            field=models.DateTimeField(null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='articletype',
            name='timestamp_lastchangedby',
            field=models.CharField(max_length=36, null=True, verbose_name='修改者'),
        ),
        migrations.AlterField(
            model_name='articletype',
            name='timestamp_lastchangedon',
            field=models.DateTimeField(null=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='documentprocess',
            name='createtime',
            field=models.DateTimeField(null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='documentprocess',
            name='info',
            field=models.TextField(null=True, verbose_name='信息'),
        ),
        migrations.AlterField(
            model_name='documentprocess',
            name='reviewer',
            field=models.CharField(max_length=36, null=True, verbose_name='审阅人'),
        ),
        migrations.AlterField(
            model_name='documentprocess',
            name='status',
            field=models.CharField(max_length=1, null=True, verbose_name='审阅状态'),
        ),
        migrations.AlterField(
            model_name='documentprocess',
            name='type',
            field=models.CharField(max_length=36, null=True, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='patchlog',
            name='creator',
            field=models.CharField(max_length=36, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='patchlog',
            name='info',
            field=models.TextField(null=True, verbose_name='信息'),
        ),
        migrations.AlterField(
            model_name='patchlog',
            name='patchtime',
            field=models.DateTimeField(null=True, verbose_name='升级时间'),
        ),
        migrations.AlterField(
            model_name='patchlog',
            name='type',
            field=models.CharField(max_length=36, null=True, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='sourcesite',
            name='icon',
            field=models.CharField(max_length=256, null=True, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='sourcesite',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='sourcesite',
            name='state_isenabled',
            field=models.CharField(max_length=1, null=True, verbose_name='是否可用'),
        ),
        migrations.AlterField(
            model_name='sourcesite',
            name='sysinit',
            field=models.CharField(max_length=1, null=True, verbose_name='系统预置'),
        ),
        migrations.AlterField(
            model_name='sourcesite',
            name='timestamp_createdby',
            field=models.CharField(max_length=36, null=True, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='sourcesite',
            name='timestamp_createdon',
            field=models.DateTimeField(null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='sourcesite',
            name='timestamp_lastchangedby',
            field=models.CharField(max_length=36, null=True, verbose_name='修改者'),
        ),
        migrations.AlterField(
            model_name='sourcesite',
            name='timestamp_lastchangedon',
            field=models.DateTimeField(null=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='sourcesite',
            name='url',
            field=models.CharField(max_length=256, null=True, verbose_name='地址'),
        ),
    ]
