# Generated by Django 3.2.16 on 2023-01-23 23:13

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0010_auto_20230102_1647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '新闻', 'verbose_name_plural': '新闻'},
        ),
        migrations.AlterModelOptions(
            name='articletype',
            options={'verbose_name': '新闻类型', 'verbose_name_plural': '新闻类型'},
        ),
        migrations.AlterModelOptions(
            name='documentprocess',
            options={'verbose_name': '工单', 'verbose_name_plural': '工单'},
        ),
        migrations.AlterModelOptions(
            name='patchlog',
            options={'verbose_name': '日志', 'verbose_name_plural': '日志'},
        ),
        migrations.AlterModelOptions(
            name='sourcesite',
            options={'verbose_name': '新闻来源', 'verbose_name_plural': '新闻来源'},
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.CharField(default=uuid.UUID('8dc8e6d7-f075-4aea-b2bd-f0e082dc1b99'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='num01',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='num02',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='pageview',
            field=models.IntegerField(default=0, null=True, verbose_name='浏览量'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pic',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publishtime',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='source',
            field=models.CharField(choices=[('1', '新浪网'), ('2', '网易新闻'), ('3', '央视网'), ('4', '搜狐新闻'), ('5', '人民日报'), ('6', '测试专用')], max_length=36, null=True, verbose_name='来源'),
        ),
        migrations.AlterField(
            model_name='article',
            name='state_isenabled',
            field=models.CharField(choices=[('1', '是'), ('0', '否')], max_length=1, null=True, verbose_name='是否可用'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.TextField(blank=True, null=True, verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='article',
            name='time01',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='time02',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='timestamp_createdon',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='timestamp_lastchangedon',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='txt01',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='txt02',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('1', '财经'), ('2', '国内'), ('3', '娱乐'), ('4', '国际'), ('5', '社会'), ('54ab4877-3b51-492c-8459-712646ee33fc', '测试专用'), ('6', '体育'), ('7', '军事'), ('8', '科技'), ('9', '报纸')], max_length=36, null=True, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='原文链接'),
        ),
        migrations.AlterField(
            model_name='articletype',
            name='icon',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='图标'),
        ),
        migrations.AlterField(
            model_name='articletype',
            name='id',
            field=models.CharField(default=uuid.UUID('33338cb0-928d-477d-858a-ebcd5491b1c6'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='articletype',
            name='num01',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articletype',
            name='showindex',
            field=models.CharField(choices=[('1', '是'), ('0', '否')], max_length=1, null=True, verbose_name='主页显示'),
        ),
        migrations.AlterField(
            model_name='articletype',
            name='state_isenabled',
            field=models.CharField(choices=[('1', '是'), ('0', '否')], max_length=1, null=True, verbose_name='是否可用'),
        ),
        migrations.AlterField(
            model_name='articletype',
            name='sysinit',
            field=models.CharField(choices=[('1', '是'), ('0', '否')], max_length=1, null=True, verbose_name='系统预置'),
        ),
        migrations.AlterField(
            model_name='articletype',
            name='time01',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articletype',
            name='timestamp_createdon',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='articletype',
            name='timestamp_lastchangedon',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='articletype',
            name='txt01',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentprocess',
            name='createtime',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='documentprocess',
            name='id',
            field=models.CharField(default=uuid.UUID('f8de7f0e-0a14-4239-a228-61d33c7bdc98'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='documentprocess',
            name='status',
            field=models.CharField(choices=[('1', '制单'), ('2', '完成'), ('3', '退回')], max_length=1, null=True, verbose_name='审阅状态'),
        ),
        migrations.AlterField(
            model_name='patchlog',
            name='id',
            field=models.CharField(default=uuid.UUID('b0da46e4-ed6e-42a2-ab84-69cb379af367'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='patchlog',
            name='patchtime',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='升级时间'),
        ),
        migrations.AlterField(
            model_name='sourcesite',
            name='icon',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='图标'),
        ),
        migrations.AlterField(
            model_name='sourcesite',
            name='id',
            field=models.CharField(default=uuid.UUID('a04cc8de-0c46-402e-8784-d2f89793f652'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sourcesite',
            name='num01',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sourcesite',
            name='state_isenabled',
            field=models.CharField(choices=[('1', '是'), ('0', '否')], max_length=1, null=True, verbose_name='是否可用'),
        ),
        migrations.AlterField(
            model_name='sourcesite',
            name='sysinit',
            field=models.CharField(choices=[('1', '是'), ('0', '否')], max_length=1, null=True, verbose_name='系统预置'),
        ),
        migrations.AlterField(
            model_name='sourcesite',
            name='time01',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sourcesite',
            name='timestamp_createdon',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='sourcesite',
            name='timestamp_lastchangedon',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='sourcesite',
            name='txt01',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sourcesite',
            name='url',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='地址'),
        ),
    ]
