# Generated by Django 3.2.16 on 2023-01-28 20:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0011_auto_20230123_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.CharField(default=uuid.UUID('53b02a0f-8237-4f6c-afbe-54ede51bd5f5'), max_length=36, primary_key=True, serialize=False, unique=True)),
                ('searchcontent', models.TextField(null=True, verbose_name='搜索内容')),
                ('searchtime', models.DateTimeField(null=True, verbose_name='搜索时间')),
                ('ip', models.CharField(max_length=30, null=True, verbose_name='操作IP')),
                ('browser', models.TextField(null=True, verbose_name='浏览器标识')),
                ('mobileflag', models.CharField(max_length=1, null=True, verbose_name='移动端标识')),
            ],
            options={
                'verbose_name': '搜索日志',
                'verbose_name_plural': '搜索日志',
                'db_table': 'searchlog',
            },
        ),
        migrations.AlterModelOptions(
            name='patchlog',
            options={'verbose_name': '升级日志', 'verbose_name_plural': '升级日志'},
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.CharField(default=uuid.UUID('c5f44c37-ffd9-469c-b758-9355ef9ceb8f'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='articletype',
            name='id',
            field=models.CharField(default=uuid.UUID('1a5ad0bc-5126-41d6-955b-0412032ea802'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='documentprocess',
            name='id',
            field=models.CharField(default=uuid.UUID('e6625aed-612d-41d0-a362-b25e50d18429'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='patchlog',
            name='id',
            field=models.CharField(default=uuid.UUID('6b008936-aedc-4f76-a83b-204306dc6fb2'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sourcesite',
            name='id',
            field=models.CharField(default=uuid.UUID('c34beea0-b112-4ce7-b6e6-1da68c3a0829'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
