# Generated by Django 3.2.16 on 2023-02-14 20:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0013_auto_20230128_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchlog',
            name='ipaddress',
            field=models.TextField(null=True, verbose_name='IP归属地'),
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.CharField(default=uuid.UUID('0794d07f-3740-40f8-adfc-eb0edc33de25'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='articletype',
            name='id',
            field=models.CharField(default=uuid.UUID('4c52e980-4c03-4184-9e09-425f8c58beca'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='documentprocess',
            name='id',
            field=models.CharField(default=uuid.UUID('eba7ca48-0abb-485f-9b40-26fd9410f5d4'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='patchlog',
            name='id',
            field=models.CharField(default=uuid.UUID('dec871e6-86a3-44b0-9830-a7794d5f0cba'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='searchlog',
            name='id',
            field=models.CharField(default=uuid.UUID('c958c69c-0b2f-44f5-b793-9306227b7731'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sourcesite',
            name='id',
            field=models.CharField(default=uuid.UUID('4470eab9-edcd-47e1-ac46-c0509d04d224'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
