# Generated by Django 3.2.16 on 2023-03-15 19:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0014_auto_20230214_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletype',
            name='var01',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.CharField(default=uuid.UUID('fdd2ec71-7930-4378-ad1c-897e71a13aba'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='articletype',
            name='id',
            field=models.CharField(default=uuid.UUID('16f591ff-61e2-42b4-a5e9-f5a8133633a5'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='documentprocess',
            name='id',
            field=models.CharField(default=uuid.UUID('650f215e-a960-4834-b34d-7d298cad5d39'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='patchlog',
            name='id',
            field=models.CharField(default=uuid.UUID('7c4487fd-c69a-4464-98e1-87bd625f7267'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='searchlog',
            name='id',
            field=models.CharField(default=uuid.UUID('a8875383-e43b-4c9f-ab74-9d1f1e33f42c'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sourcesite',
            name='id',
            field=models.CharField(default=uuid.UUID('752b6677-faea-419a-b36a-0a0f01587082'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
