# Generated by Django 3.2.16 on 2023-03-15 19:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0015_auto_20230315_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.CharField(default=uuid.UUID('c57aa6a7-5b7c-423e-8054-fdea426ca51b'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='articletype',
            name='id',
            field=models.CharField(default=uuid.UUID('ed9d682c-b99c-4ef1-b11d-077c54474310'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='articletype',
            name='var01',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='documentprocess',
            name='id',
            field=models.CharField(default=uuid.UUID('faf693d9-d81c-4b8e-8d7a-af5ce1205bf4'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='patchlog',
            name='id',
            field=models.CharField(default=uuid.UUID('83bdee9e-03e8-475d-9f36-a3090795e194'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='searchlog',
            name='id',
            field=models.CharField(default=uuid.UUID('8d67159f-1d36-4284-87f2-55d6fd33f79f'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sourcesite',
            name='id',
            field=models.CharField(default=uuid.UUID('39f3afb8-6b4f-481d-9944-067ff5a67261'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
