# Generated by Django 3.2.16 on 2023-03-15 19:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0016_auto_20230315_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articletype',
            name='var01',
        ),
        migrations.AddField(
            model_name='article',
            name='var01',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='var02',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.CharField(default=uuid.UUID('39e38a1d-a281-4b7f-a20a-20273f10002c'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='articletype',
            name='id',
            field=models.CharField(default=uuid.UUID('59098e90-e509-4eb0-8b6f-f6e047665898'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='documentprocess',
            name='id',
            field=models.CharField(default=uuid.UUID('3b31792a-62c5-4d40-b60a-82f214b59b5d'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='patchlog',
            name='id',
            field=models.CharField(default=uuid.UUID('8104f9f4-eb00-4190-87d2-51ae738a1b53'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='searchlog',
            name='id',
            field=models.CharField(default=uuid.UUID('41397c2b-6895-4580-9e28-801c6a7e780f'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sourcesite',
            name='id',
            field=models.CharField(default=uuid.UUID('dfef9ecd-6bc2-4606-acba-f60daaebd3fe'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
