# Generated by Django 3.2.16 on 2023-03-15 19:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0017_auto_20230315_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.CharField(default=uuid.UUID('2f8f1fee-185c-4508-b0c5-036b6387519a'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='var01',
            field=models.CharField(blank=True, db_index=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='articletype',
            name='id',
            field=models.CharField(default=uuid.UUID('75a173b1-5975-45c2-b07c-c9ac1aa63212'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='documentprocess',
            name='id',
            field=models.CharField(default=uuid.UUID('f751608b-2640-473a-ad0b-07e3e2c35538'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='patchlog',
            name='id',
            field=models.CharField(default=uuid.UUID('bccdd9d7-f9b9-4d92-b147-dbc38604572b'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='searchlog',
            name='id',
            field=models.CharField(default=uuid.UUID('8e322e86-27d0-44fe-b7fd-8fedb867ce3b'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sourcesite',
            name='id',
            field=models.CharField(default=uuid.UUID('3933f3bd-0d91-4562-8bac-a7e6e8a36a78'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
