# Generated by Django 3.2.16 on 2023-03-15 21:54

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0018_auto_20230315_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.CharField(default=uuid.UUID('210bf25b-871c-4307-aa1b-3b5cd38428e0'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='publishtime',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, null=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True, verbose_name='原文链接'),
        ),
        migrations.AlterField(
            model_name='article',
            name='var01',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='articletype',
            name='id',
            field=models.CharField(default=uuid.UUID('9c283d68-2761-4db1-afab-f0992a9a2d34'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='documentprocess',
            name='id',
            field=models.CharField(default=uuid.UUID('e9f2ecc8-10d1-483a-b1ba-64b0371834c2'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='patchlog',
            name='id',
            field=models.CharField(default=uuid.UUID('5dd90e84-1b13-44c5-a9ba-d1d791b544f6'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='searchlog',
            name='id',
            field=models.CharField(default=uuid.UUID('55a9e945-e30a-4a55-a237-26f31aa1a66c'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sourcesite',
            name='id',
            field=models.CharField(default=uuid.UUID('bf2af1ce-b787-4d06-9bc9-e5e94214aaaa'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
