# Generated by Django 3.2.16 on 2023-03-15 21:57

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0019_auto_20230315_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.CharField(default=uuid.UUID('bb1f25c0-81f8-4a53-bb0f-8977c42320a0'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='publishtime',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='var01',
            field=models.CharField(blank=True, db_index=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='articletype',
            name='id',
            field=models.CharField(default=uuid.UUID('78292f76-4b13-4074-bfd2-f042c11a4fc9'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='documentprocess',
            name='id',
            field=models.CharField(default=uuid.UUID('d1eac0c5-814b-468a-b775-bd3677d87d11'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='patchlog',
            name='id',
            field=models.CharField(default=uuid.UUID('c67538ea-37da-4074-be4d-8dc7183b2bf8'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='searchlog',
            name='id',
            field=models.CharField(default=uuid.UUID('d8f6b83a-c48b-47b5-b475-68bfceff8ba5'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sourcesite',
            name='id',
            field=models.CharField(default=uuid.UUID('26564727-f7b5-4ca2-9e6e-ce0ad3a2f4d4'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
